apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: Go-thu-oct-29
          artifact-id: e777d622-42cb-4ac2-bd67-5f920b50afdf
          target-environment: ecr-qa      
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: pre-prod
          artifact-id: e777d622-42cb-4ac2-bd67-5f920b50afdf
          target-environment: aspm-pre-production