apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: Go-thu-oct-29
          artifact-id: 352a1dcb-ec31-4846-b549-9f680cad929f
          target-environment: ecr-qa      