apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: Go-thu-oct-29
          artifact-id: 6a8bb3f3-639a-474b-b433-7c7074d9d8d2
          target-environment: ecr-qa      