apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: Go-thu-oct-29
          artifact-id: 6c1fa385-ff95-4040-afb3-1fb6293df404
          target-environment: ecr-qa      